exclude:
-/.gradle/.*
-/bin/.idea/.*
-/Final TP & Triggers/.*
-/LPOO1617_T2G5/.*
-/TP1/.*
-/Prairie King/.idea/.*
-/Prairie King/desktop/.*
-/Prairie King/.gitignore
-/Prairie King/gradle/.*
-/Prairie King/html/.*
-/Prairie King/Mock-Up.bmpr
component_depth: 7
languages:
- java